#!/usr/bin/env python3
"""
generate_makefile.py

Fortran研究コード用 Makefile 自動生成スクリプト。

Windows + MS-MPI + gfortran 対応版。
MS-MPI のパスに空白が含まれるため、Makefile中では必ず引用符で囲む。
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Dict, List, Set


MODULE_DEF_RE = re.compile(r"^\s*module\s+([a-zA-Z_]\w*)\s*$", re.IGNORECASE)
USE_RE = re.compile(r"^\s*use\s*(?:,\s*intrinsic\s*)?(?:::)?\s*([a-zA-Z_]\w*)", re.IGNORECASE)


def make_path(path: Path) -> str:
    return str(path).replace("\\", "/")


def object_path(src: Path, src_root: Path, obj_root: Path) -> Path:
    rel = src.relative_to(src_root)
    return obj_root / rel.with_suffix(".o")


def scan_sources(src_root: Path) -> List[Path]:
    return sorted(src_root.rglob("*.f90"))


def parse_fortran_file(path: Path) -> tuple[Set[str], Set[str]]:
    defined: Set[str] = set()
    used: Set[str] = set()

    lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()

    for line in lines:
        line = line.split("!")[0].strip()
        if not line:
            continue

        m = MODULE_DEF_RE.match(line)
        if m:
            name = m.group(1).lower()
            if name != "procedure":
                defined.add(name)
            continue

        m = USE_RE.match(line)
        if m:
            used.add(m.group(1).lower())

    return defined, used


def build_deps(sources: List[Path]) -> Dict[Path, Set[Path]]:
    module_to_src: Dict[str, Path] = {}
    uses_by_src: Dict[Path, Set[str]] = {}

    for src in sources:
        defs, uses = parse_fortran_file(src)
        uses_by_src[src] = uses
        for name in defs:
            module_to_src[name] = src

    ignored = {
        "iso_fortran_env",
        "omp_lib",
        "mpi",
    }

    deps: Dict[Path, Set[Path]] = {src: set() for src in sources}

    for src, uses in uses_by_src.items():
        for name in uses:
            if name in ignored:
                continue
            provider = module_to_src.get(name)
            if provider is not None and provider != src:
                deps[src].add(provider)

    return deps


def generate_makefile(
    sources: List[Path],
    deps: Dict[Path, Set[Path]],
    src_root: Path,
    obj_root: Path,
    exe: str,
    mpi_root: str,
) -> str:
    objs = [object_path(src, src_root, obj_root) for src in sources]

    lines: List[str] = []

    lines.append("# Auto-generated Makefile")
    lines.append("# Generated by generate_makefile.py")
    lines.append("")
    lines.append("FC = gfortran")
    lines.append("")
    lines.append(f'MPI_ROOT = {mpi_root}')
    lines.append('MPI_INC = $(MPI_ROOT)/Include')
    lines.append('MPI_INC_X64 = $(MPI_ROOT)/Include/x64')
    lines.append('MPI_LIB = $(MPI_ROOT)/Lib/x64')
    lines.append("")
    lines.append(f"SRC_ROOT = {make_path(src_root)}")
    lines.append(f"OBJ_ROOT = {make_path(obj_root)}")
    lines.append(f"EXE = {exe}")
    lines.append("")
    lines.append("FFLAGS = -fopenmp -fallow-invalid-boz -fallow-argument-mismatch")
    lines.append('INCLUDES = -I. -I$(SRC_ROOT) -I"$(MPI_INC)" -I"$(MPI_INC_X64)"')
    lines.append('LIBS = -L"$(MPI_LIB)" -lmsmpifec -lmsmpi -fopenmp')
    lines.append("")
    lines.append("OBJS = \\")
    for i, obj in enumerate(objs):
        suffix = " \\" if i < len(objs) - 1 else ""
        lines.append(f"\t{make_path(obj)}{suffix}")
    lines.append("")
    lines.append(".PHONY: all clean run")
    lines.append("")
    lines.append("all: $(EXE)")
    lines.append("")
    lines.append("$(EXE): $(OBJS)")
    lines.append("\t$(FC) $(OBJS) $(LIBS) -o $(EXE)")
    lines.append("")

    for src in sources:
        obj = object_path(src, src_root, obj_root)
        obj_s = make_path(obj)
        src_s = make_path(src)

        dep_objs = [object_path(d, src_root, obj_root) for d in sorted(deps[src])]
        dep_s = " ".join(make_path(d) for d in dep_objs)

        target = f"{obj_s}: {src_s}"
        if dep_s:
            target += " " + dep_s

        lines.append(target)
        obj_dir = make_path(obj.parent)
        lines.append(f'\t@if not exist "{obj_dir}" mkdir "{obj_dir}"')
        lines.append(f"\t$(FC) -c {src_s} $(INCLUDES) $(FFLAGS) -J$(OBJ_ROOT) -o {obj_s}")
        lines.append("")

    lines.append("run: $(EXE)")
    lines.append("\tmpiexec -n 4 $(EXE)")
    lines.append("")
    lines.append("clean:")
    lines.append("\t-del /Q $(EXE) 2>nul")
    lines.append("\t-del /Q *.mod 2>nul")
    lines.append("\t-if exist $(OBJ_ROOT) rmdir /S /Q $(OBJ_ROOT)")
    lines.append("")

    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--src-root", default="src")
    parser.add_argument("--obj-root", default="build")
    parser.add_argument("--exe", default="solver.exe")
    parser.add_argument("--mpi-root", default="C:/Program Files (x86)/Microsoft SDKs/MPI")
    parser.add_argument("--output", default="Makefile")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    src_root = Path(args.src_root)
    obj_root = Path(args.obj_root)

    if not src_root.exists():
        print(f"[ERROR] src root not found: {src_root}")
        return 1

    sources = scan_sources(src_root)

    if not sources:
        print(f"[ERROR] no .f90 files found under: {src_root}")
        return 1

    deps = build_deps(sources)

    text = generate_makefile(
        sources=sources,
        deps=deps,
        src_root=src_root,
        obj_root=obj_root,
        exe=args.exe,
        mpi_root=args.mpi_root,
    )

    Path(args.output).write_text(text, encoding="utf-8")

    print("[OK] Makefile generated.")
    print(f"  output: {args.output}")
    print("")
    print("Next:")
    print("  mingw32-make clean")
    print("  mingw32-make")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
