#!/usr/bin/env python3
"""
generate_makefile.py

Fortran研究コード用 Makefile 自動生成スクリプト。

目的:
  - src/ 配下の .f90 ファイルを自動探索する。
  - module/use の依存関係を簡易解析する。
  - 依存順にコンパイルできる Makefile を生成する。
  - Windows + MS-MPI + gfortran に対応する。

想定ディレクトリ構成:
  project/
  ├── src/
  │   ├── main/
  │   │   └── main.f90
  │   ├── core/
  │   │   ├── mod_precision.f90
  │   │   └── mod_constants.f90
  │   └── mpi/
  │       └── module_mpi_TW_NEC.f90
  └── generate_makefile.py

使い方:
  python generate_makefile.py

出力:
  Makefile

コンパイル:
  mingw32-make
  または
  make
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Dict, List, Set


MODULE_DEF_RE = re.compile(r"^\s*module\s+([a-zA-Z_]\w*)\s*$", re.IGNORECASE)
USE_RE = re.compile(r"^\s*use\s*(?:,\s*intrinsic\s*)?(?:::)?\s*([a-zA-Z_]\w*)", re.IGNORECASE)


def normalize_path_for_make(path: Path) -> str:
    """Makefile用に / 区切りへ変換する。"""
    return str(path).replace("\\", "/")


def object_name(src: Path, src_root: Path, obj_root: Path) -> Path:
    """src/core/a.f90 -> build/core/a.o のように対応させる。"""
    rel = src.relative_to(src_root)
    return obj_root / rel.with_suffix(".o")


def scan_sources(src_root: Path) -> List[Path]:
    return sorted(src_root.rglob("*.f90"))


def parse_fortran_file(path: Path) -> tuple[Set[str], Set[str]]:
    """
    Fortranファイルから定義moduleとuse moduleを簡易抽出する。
    submoduleや複雑なプリプロセッサには未対応。
    """
    defined: Set[str] = set()
    used: Set[str] = set()

    text = path.read_text(encoding="utf-8", errors="ignore").splitlines()

    for line in text:
        # コメント除去
        line_no_comment = line.split("!")[0].strip()
        if not line_no_comment:
            continue

        m_def = MODULE_DEF_RE.match(line_no_comment)
        if m_def:
            name = m_def.group(1).lower()
            # module procedure は除外
            if name != "procedure":
                defined.add(name)
            continue

        m_use = USE_RE.match(line_no_comment)
        if m_use:
            used.add(m_use.group(1).lower())

    return defined, used


def build_dependency_map(sources: List[Path]) -> tuple[Dict[str, Path], Dict[Path, Set[Path]]]:
    module_to_src: Dict[str, Path] = {}
    src_uses: Dict[Path, Set[str]] = {}

    for src in sources:
        defs, uses = parse_fortran_file(src)
        for mod in defs:
            module_to_src[mod] = src
        src_uses[src] = uses

    deps: Dict[Path, Set[Path]] = {src: set() for src in sources}

    ignored_modules = {
        "iso_fortran_env",
        "omp_lib",
        "mpi",
    }

    for src, uses in src_uses.items():
        for mod in uses:
            if mod in ignored_modules:
                continue
            provider = module_to_src.get(mod)
            if provider is not None and provider != src:
                deps[src].add(provider)

    return module_to_src, deps


def makefile_text(
    sources: List[Path],
    deps: Dict[Path, Set[Path]],
    src_root: Path,
    obj_root: Path,
    exe_name: str,
    mpi_root: str,
) -> str:
    lines: List[str] = []

    objs = [object_name(src, src_root, obj_root) for src in sources]

    lines.append("# Auto-generated Makefile")
    lines.append("# Generated by generate_makefile.py")
    lines.append("")
    lines.append("FC = gfortran")
    lines.append("")
    lines.append(f"MPI_ROOT = {mpi_root}")
    lines.append("MPI_INC = $(MPI_ROOT)/Include")
    lines.append("MPI_INC_X64 = $(MPI_ROOT)/Include/x64")
    lines.append("MPI_LIB = $(MPI_ROOT)/Lib/x64")
    lines.append("")
    lines.append("EXE = " + exe_name)
    lines.append("")
    lines.append("# MS-MPI + gfortran compatibility flags")
    lines.append("FFLAGS = -fopenmp -fallow-invalid-boz -fallow-argument-mismatch")
    lines.append("INCLUDES = -I. -I$(SRC_ROOT) -I$(MPI_INC) -I$(MPI_INC_X64)")
    lines.append("LIBS = -L$(MPI_LIB) -lmsmpifec -lmsmpi -fopenmp")
    lines.append("")
    lines.append(f"SRC_ROOT = {normalize_path_for_make(src_root)}")
    lines.append(f"OBJ_ROOT = {normalize_path_for_make(obj_root)}")
    lines.append("")
    lines.append("OBJS = \\")
    for i, obj in enumerate(objs):
        suffix = " \\" if i < len(objs) - 1 else ""
        lines.append(f"\t{normalize_path_for_make(obj)}{suffix}")
    lines.append("")
    lines.append(".PHONY: all clean run")
    lines.append("")
    lines.append("all: $(EXE)")
    lines.append("")
    lines.append("$(EXE): $(OBJS)")
    lines.append("\t$(FC) $(OBJS) $(LIBS) -o $(EXE)")
    lines.append("")

    for src in sources:
        obj = object_name(src, src_root, obj_root)
        obj_s = normalize_path_for_make(obj)
        src_s = normalize_path_for_make(src)
        dep_objs = [object_name(d, src_root, obj_root) for d in sorted(deps[src])]
        dep_s = " ".join(normalize_path_for_make(d) for d in dep_objs)
        target_line = f"{obj_s}: {src_s}"
        if dep_s:
            target_line += " " + dep_s
        lines.append(target_line)
        # Windows cmdでもLinux makeでもある程度通るように mkdir を分ける
        obj_dir = normalize_path_for_make(obj.parent)
        lines.append(f"\t@if not exist \"{obj_dir}\" mkdir \"{obj_dir}\"")
        lines.append(f"\t$(FC) -c {src_s} $(INCLUDES) $(FFLAGS) -J$(OBJ_ROOT) -o {obj_s}")
        lines.append("")

    lines.append("run: $(EXE)")
    lines.append("\tmpiexec -n 4 $(EXE)")
    lines.append("")
    lines.append("clean:")
    lines.append("\t-del /Q $(EXE) 2>nul")
    lines.append("\t-del /Q *.mod 2>nul")
    lines.append("\t-if exist $(OBJ_ROOT) rmdir /S /Q $(OBJ_ROOT)")
    lines.append("")

    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Makefile for Fortran project.")
    parser.add_argument("--src-root", default="src", help="Source root directory. Default: src")
    parser.add_argument("--obj-root", default="build", help="Object/mod output directory. Default: build")
    parser.add_argument("--exe", default="solver.exe", help="Executable name. Default: solver.exe")
    parser.add_argument(
        "--mpi-root",
        default="C:/Program Files (x86)/Microsoft SDKs/MPI",
        help="MS-MPI root path.",
    )
    parser.add_argument("--output", default="Makefile", help="Output Makefile path.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    src_root = Path(args.src_root)
    obj_root = Path(args.obj_root)

    if not src_root.exists():
        print(f"[ERROR] Source root not found: {src_root}")
        return 1

    sources = scan_sources(src_root)

    if not sources:
        print(f"[ERROR] No .f90 files found under: {src_root}")
        return 1

    _, deps = build_dependency_map(sources)

    text = makefile_text(
        sources=sources,
        deps=deps,
        src_root=src_root,
        obj_root=obj_root,
        exe_name=args.exe,
        mpi_root=args.mpi_root,
    )

    Path(args.output).write_text(text, encoding="utf-8")

    print("[OK] Makefile generated.")
    print(f"  Source root : {src_root}")
    print(f"  Object root : {obj_root}")
    print(f"  Output      : {args.output}")
    print(f"  Executable  : {args.exe}")
    print("")
    print("Next:")
    print("  mingw32-make")
    print("or")
    print("  make")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
